name: Release new action version
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'run release action reason'
        required: false
        type: string
        default: 'manually test'
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3

      - name: Check Go Version and Install Go Dep
        run: |
          go version
          go mod vendor

      - name: Build
        run: make all

      - name: Generate Release.txt
        run: |
          echo ${{ github.sha }} > Release.txt
          cat Release.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: bin-artifact
          path: |
            bin/
            Release.txt
            LICENSE
